export const Constants = {
  LOGIN: "LOGIN",
  LOGIN_FAILED: "LOGIN FAILED",
  LOGIN_SUCCESS: "LOGIN SUCCESS",
  USERNAME_CHANGED: "USERNAME CHANGED",
  PASSWORD_CHANGED: "PASSWORD CHANGED",
  CREDENTIALS_CHANGED: "CREDENTIALS CHANGED",
  INPUT_CHANGED:"INPUT CHANGED",
  ADD_WORKOUT:"ADD WORKOUT",
  SAVING_WORKOUT:"SAVE WORKOUT",
  SAVING_WORKOUT_SUCCESSFUL:"SAVING_WORKOUT_SUCCESSFUL"
};
